HZX-287: Data policies demo
hazelcast/hazelcast-flow-public-demos pull request #31
Opened 2024-10-29 11:11 UTC by pmcgleenon

https://hazelcast.atlassian.net/browse/HZX-287

Added the stock ticker demo to illustrate how Data Policies work.   Components include:
 - Flow
 - Management Center
 - kafka
 - stock-ticker producer

There is a taxi project with a definition for the Stock Ticker events and some example policies

2024-10-29 12:13 UTC, amandalindsay requested changes
looks good, just made some minor tweaks to capitalisation. Left 'Data Access Policies' as is, as assuming this is a proper name?

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +based on the User's Role.
```suggestion
based on the user's role.
```

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +| admin      | Full access | Full access to all features      |
```suggestion
| admin      | full access | Full access to all features      |
```

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +based on the User's Role.
assuming we don't need to use initial caps on User's Role? Or is this a proper name?

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +- [docker-compose](https://docs.docker.com/compose/install/)
```suggestion
- [Docker-compose](https://docs.docker.com/compose/install/)
```

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +The following steps will run a local instance of the Hazelcast Flow using the default configuration file (`docker-compose.yml`):
```suggestion
The following steps will run a local instance of Hazelcast Flow using the default configuration file (`docker-compose.yml`):
```

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +1. Clone this repository.
```suggestion
1. Clone this repository
```

2024-10-29 12:13 UTC, amandalindsay commented on stock-ticker/README.md
> +1. Clone this repository.
Remove full stops from end of bullets

2024-10-29 13:47 UTC, pmcgleenon commented
> looks good, just made some minor tweaks to capitalisation. Left 'Data Access Policies' as is, as assuming this is a proper name?

thanks for the feedback, I've applied those changes

2024-10-30 11:32 UTC, amandalindsay approved these changes

2024-11-06 09:31 UTC, merged